version: '3'
services:
  redis1:
    image: redis
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - 7000:7000
    networks:
      - redis-net
  redis2:
    image: redis
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - 7001:7001
    networks:
      - redis-net
  redis3:
    image: redis
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - 7002:7002
    networks:
      - redis-net
networks:
  redis-net:
